"""autogenerated migration

Revision ID: 2e8808640f25
Revises: 747623dff40e
Create Date: 2026-01-05 21:36:02.958896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8808640f25'
down_revision: Union[str, Sequence[str], None] = '747623dff40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('note_path', sa.String(), nullable=True))
    op.add_column('account', sa.Column('github_token', sa.String(), nullable=True))
    op.add_column('account', sa.Column('github_repo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'github_repo')
    op.drop_column('account', 'github_token')
    op.drop_column('account', 'note_path')
    # ### end Alembic commands ###
