"""Add fields to account model

Revision ID: 747623dff40e
Revises: 491e0e246a1d
Create Date: 2025-12-28 16:39:55.320278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747623dff40e'
down_revision: Union[str, Sequence[str], None] = '491e0e246a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(), nullable=True))
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.true()))
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(), nullable=True))
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_id', sa.String(), nullable=True))
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('email',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.create_index(op.f('ix_account_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_account_email'))
        batch_op.alter_column('email', existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('oauth_id')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('oauth_provider')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('picture')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('name')
    # ### end Alembic commands ###
