"""remove false integrations

Revision ID: d304e46a8fd0
Revises: 2e8808640f25
Create Date: 2026-01-06 14:29:39.807254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd304e46a8fd0'
down_revision: Union[str, Sequence[str], None] = '2e8808640f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'github_token')
    op.drop_column('account', 'note_path')
    op.drop_column('account', 'github_repo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('github_repo', sa.VARCHAR(), nullable=True))
    op.add_column('account', sa.Column('note_path', sa.VARCHAR(), nullable=True))
    op.add_column('account', sa.Column('github_token', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
